[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "test"
solc = "0.8.20"
auto_detect_solc = true
remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/',
  'forge-std/=lib/forge-std/src/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config

[rpc_endpoints]
anvil = "http://localhost:8545"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
